version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: heya-pos-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: heya_pos
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d heya_pos"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: