[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = [
  "npm run build --workspace=@heya-pos/types",
  "npm run build --workspace=@heya-pos/utils",
  "cd apps/api && npx prisma generate",
  "cd apps/api && npm run build"
]

[start]
cmd = "cd apps/api && npm run start:prod"

[variables]
NPM_CONFIG_PRODUCTION = 'false'
NODE_ENV = 'production'