[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = [
  "npm run build --workspace=@heya-pos/types",
  "npm run build --workspace=@heya-pos/utils",
  "npm run build --workspace=@heya-pos/ui",
  "cd apps/api && npx prisma generate && cd ../..",
  "npm run build --workspace=api"
]

[start]
cmd = "cd apps/api && npm run start:prod"

[variables]
NPM_CONFIG_PRODUCTION = 'false'