# fly.toml app configuration file generated for heya-pos-api on 2025-07-24T10:56:37+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'heya-pos-api'
primary_region = 'syd'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  dockerfile = "../../Dockerfile.api"
  context = "../.."

[env]
  DATABASE_CONNECTION_LIMIT = '20'
  NODE_ENV = 'production'
  PORT = '3000'
  PRISMA_CLIENT_ENGINE_TYPE = 'binary'
  TZ = 'Australia/Sydney'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1