[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["cp package.json.standalone package.json && npm install"]

[phases.build]
cmds = [
  "npx prisma generate",
  "npm run build"
]

[start]
cmd = "npm run start:prod"